<a href="https://colab.research.google.com/github/salihaliyi73/PyTorch-works/blob/main/Copy_of_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch


In [4]:
import numpy as np

***LISTS/ARRAY***

In [2]:
my_list =[[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

***NUMPY ARRAY***

In [14]:
np1 = np.random.rand(3,4,5)
np1

array([[[0.36199796, 0.23588995, 0.26188654, 0.24116611, 0.08381165],
        [0.07248695, 0.95878366, 0.53791778, 0.29647987, 0.40636174],
        [0.69508253, 0.76590714, 0.22862127, 0.29779795, 0.70146807],
        [0.89220887, 0.06864518, 0.91176866, 0.22239406, 0.89016566]],

       [[0.37233219, 0.01464281, 0.63545182, 0.22644237, 0.96454957],
        [0.58325393, 0.77879601, 0.42374339, 0.44713052, 0.40754362],
        [0.29926135, 0.84683554, 0.33086216, 0.04326201, 0.5424888 ],
        [0.58082797, 0.93040052, 0.2495614 , 0.94635502, 0.90236696]],

       [[0.48632037, 0.56469395, 0.51301338, 0.08944414, 0.84608358],
        [0.44927203, 0.52646179, 0.41860952, 0.43092335, 0.20783669],
        [0.61126726, 0.40243061, 0.59030329, 0.81648222, 0.31705535],
        [0.18859112, 0.51546629, 0.29177985, 0.25308191, 0.73493164]]])

In [6]:
np1.dtype

dtype('float64')

In [12]:
tensor_2d = torch.randn(3,4,5)

In [13]:
tensor_2d

tensor([[[-0.6166, -0.4695,  0.4692,  0.3938, -1.5787],
         [ 0.4564, -0.7722,  0.0461, -0.6428,  0.7924],
         [-1.6819,  1.0864,  1.6196, -1.9352,  1.5009],
         [ 0.5355, -0.5220, -1.1701, -0.4487, -0.0476]],

        [[ 0.5017, -1.1600, -2.0570,  0.5991,  0.9005],
         [ 0.0914,  0.4303, -0.2748, -0.5226, -0.6178],
         [-0.8967, -1.6324,  0.3199,  0.1577,  0.5032],
         [ 0.1984,  0.5004, -0.3134, -1.2030,  0.4535]],

        [[ 0.1304, -0.4517,  0.4651, -1.5018,  0.2241],
         [-0.2006,  0.4384, -0.4355,  0.1255, -1.6424],
         [ 0.6134,  0.0740, -1.0978, -0.1917, -0.1253],
         [ 1.0971, -0.5086,  0.9874,  1.7120, -2.0542]]])

In [11]:
tensor_2d.dtype

torch.float32

In [15]:
#create tensor from Numpy array
my_tensor= torch.tensor(np1)
my_tensor

tensor([[[0.3620, 0.2359, 0.2619, 0.2412, 0.0838],
         [0.0725, 0.9588, 0.5379, 0.2965, 0.4064],
         [0.6951, 0.7659, 0.2286, 0.2978, 0.7015],
         [0.8922, 0.0686, 0.9118, 0.2224, 0.8902]],

        [[0.3723, 0.0146, 0.6355, 0.2264, 0.9645],
         [0.5833, 0.7788, 0.4237, 0.4471, 0.4075],
         [0.2993, 0.8468, 0.3309, 0.0433, 0.5425],
         [0.5808, 0.9304, 0.2496, 0.9464, 0.9024]],

        [[0.4863, 0.5647, 0.5130, 0.0894, 0.8461],
         [0.4493, 0.5265, 0.4186, 0.4309, 0.2078],
         [0.6113, 0.4024, 0.5903, 0.8165, 0.3171],
         [0.1886, 0.5155, 0.2918, 0.2531, 0.7349]]], dtype=torch.float64)