<a href="https://colab.research.google.com/github/salihaliyi73/PyTorch-works/blob/main/tensors_operation_in_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
my_torch =torch.arange(10)

In [4]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and View
my_torch =my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# reshape if we don't know the number of items in tensors using -1
my_torch2=torch.arange(15)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_torch2=my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [19]:
my_torch2=my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [20]:
# VIEW
mytorch3=torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
mytorch4=mytorch3.view(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
mytorch4=mytorch3.view(2,-1)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
# The difference of reshapw and view in tensors of pytorch
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [24]:
# with reshape and view, they will update
my_torch5 =torch.arange(10)
my_torch5


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch6=my_torch5.reshape(2,5)

In [26]:
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch5[1]=1995
my_torch5

tensor([   0, 1995,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
my_torch6

tensor([[   0, 1995,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [29]:
# Slices
my_torch7=torch.arange(10)
my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#take specific item
my_torch7[7]

tensor(7)

In [33]:
# Grab(take) slice
my_torch8=my_torch7.reshape(5,2)
my_torch8


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [34]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [35]:
# Return Column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
m