<a href="https://colab.research.google.com/github/salihaliyi73/PyTorch-works/blob/main/Tensor_math_operarion_for_deep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**

In [2]:
import torch

In [ ]:
import numpy as np

In [5]:
#Create tensor
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])
tensor_a
tensor_b


tensor([5, 6, 7, 8])

**Addition**

In [7]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

**Addition longhand**

In [8]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

**substruction**

In [9]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [10]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [11]:
#multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
torch.mul(tensor_b,tensor_a)

tensor([ 5, 12, 21, 32])

**division**
Automatically convert it to float

In [13]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

**div long**

In [14]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

**Remainders**

In [15]:
tensor_b% tensor_a

tensor([0, 0, 1, 0])

**remainder longhand**

In [16]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

**Exponents/Power**

In [6]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

**ANOTHER WAY TO WRITE LOONGHAND**

In [7]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

**Reassignment**

In [8]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
tensor_a

tensor([ 6,  8, 10, 12])